Project/config/routes.rb
Rails.application.routes.draw do

  resources :blogs

  get 'answers/indexshow'

 

  resources :posts
 resources :widgets
  resources :answers

  resources :consultancies

  devise_for :views
  devise_for :users
  resources :events
 resources :pitches do
    member do
     get 'evaluateIdeaConsultant' 
     get 'submitTheForm'
     post 'submitTheEvaluation'
    end
  end
  resources :conversations do
  resources :messages
 end

resources :posts, :has_many => :answers

  resources :consultancies
  get 'pages/home'
  get 'users/show'
  get 'events/userview'
  get 'users/index'
  get 'users/edit'
  get 'pages/home2'
  get 'pages/home3'
  get 'pages/signup'
  get 'pages/login'
  get 'posts/index'
  root 'pages#home'
  get 'approve' => 'consultancies#approve'
  post 'approve' => 'consultancies#approve'
  match 'users/:id/approve'=> 'users#approve_user', :via => [:get], as: 'approve_user'
  

end

Project/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :post
  


end

Project/app/models/blog.rb
class Blog < ActiveRecord::Base
end

Project/app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base
	belongs_to :blog
end

Project/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pitches

end

Project/app/models/conversation.rb
class Conversation < ActiveRecord::Base

# belongs_to :sender, :foreign_key => :sender_id, class_name: ‘User’
# belongs_to :recipient, :foreign_key => :recipient_id, class_name: ‘User’

has_many :messages, dependent: :destroy
validates_uniqueness_of :sender_id, :scope => :recipient_id

# scope :between, -> (sender_id,recipient_id) do
#  where(“(conversations.sender_id =? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)”, sender_id,recipient_id, recipient_id, sender_id)
#  end
end

Project/app/models/createComment.rb
class CreateComments < ActiveRecord::Migration
  def change
    create_table :comments do |t|
      t.string :commenter
      t.text :body
 
      # this line adds an integer column called `article_id`.
      t.references :article, index: true
 
      t.timestamps null: false
    end
    add_foreign_key :comments, :pitches
  end
end

Project/app/models/evalution.rb
class Evalution < ActiveRecord::Base
  belongs_to :user
  belongs_to :pitch
end

Project/app/models/friendship.rb
class Friendship < ActiveRecord::Base
	  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

Project/app/models/message.rb
class Message < ActiveRecord::Base
 belongs_to :conversation
 belongs_to :user
 validates_presence_of :body, :conversation_id, :user_id
 
	def message_time
		t = Time.now
		t.strftime(" %a, %d %b at %I:%M%p")            #=> example: "wed, 29 Apr at 01:20AM"
	end
end

Project/app/models/notification.rb
class Notification < ActiveRecord::Base
end

Project/app/models/pitch.rb
class Pitch < ActiveRecord::Base
  has_many :evalutions
	def user
		return User.find_by_email(self.email)
	end

	def consultancies
		return Consultancy.where("pitch_id =?", self.id)
	end
end

Project/app/models/post.rb
class Post < ActiveRecord::Base
  # validates_presence_of :name, :title
  # validates_length_of :title, :minimum => 5
  has_many :answers
end

Project/app/models/team.rb
class Team < ActiveRecord::Base
	  has_many :users

		 
  belongs_to :pitch, :class_name => "Pitch"
end

Project/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :evalutions
        def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end


  def pitches
    return Pitch.where("email =?",self.email)
  end

end

Project/app/models/widget.rb
class Widget < ActiveRecord::Base
end

Project/app/controllers/pitches_controller.rb
class PitchesController < ApplicationController

  respond_to :html, :json


    # http_basic_authenticate_with name: "nageeb", password: "12345678", except: [:index, :show]


  def index
      @pitches = Pitch.paginate :per_page => 9, :page => params[:page]

  end

  def show
    if  current_user.is_Ideator || current_user.is_Idea_Consultant || current_user.admin
        @pitch = Pitch.find(params[:id])
        @consultancies = @pitch.consultancies
    else
      redirect_to :back
    end
  end

  def new
    @pitch = Pitch.new
  end


  def create
    @pitch = Pitch.new(pitch_params)
    if @pitch.save
      redirect_to @pitch
    else
      render 'new'
    end
  end


  def edit
      @pitch = Pitch.find(params[:id])

  end

  def update

      @pitch = Pitch.find(params[:id])
      if @pitch.update(pitch_params)
        redirect_to @pitch
      else
        render 'edit'
      end
  end


    def destroy
    @pitch = Pitch.find(params[:id])
    @pitch.destroy
 
    redirect_to pitches_path
  end


  #private
  def pitch_params
    params.require(:pitch).permit(:title, :brief_description, :full_description, :url, :email, :username)
  end







 #This method is that the ideaConsultant is to be evaluated by the ideator 
 #Author: Mariam Afifi
  def evaluateIdeaConsultant
     @pitch = Pitch.find(params[:id])
    if ! current_user.is_Ideator?
    redirect_to pitches_path, alert: "you are not allowed to evaluate"
    end
 end
 

 #This method is to submit the evaluation form
 #Author: Mariam Afifi
  def submitTheForm
  user = User.find_by_email(params[:IdeaConsultantEmailAddress])
  if user.nil?
    redirect_to pitches_path, alert: "He is not an idea consultant"
  else
    redirect_to pitches_path, notice: "The form has been submitted successfuly"
 end
end

 #This method is to post the evaluation 
 #Author: Mariam Afifi
  def submitTheEvaluation
  @pitch = Pitch.find(params[:id])
  if current_user.is_Idea_Consultant
     current_user.evalutions.create(pitch: @pitch, comment: params[:Evaluate])
     redirect_to @pitch, notice: "your evaluation has been posted"
  else
     redirect_to @pitch, alert: "you are not allowed to evaluate"
    end
  end

end

Project/app/helpers/answers_helper.rb
module AnswersHelper
end

Project/app/helpers/blogs_helper.rb
module BlogsHelper
end

Project/app/helpers/comment_helper.rb
module CommentHelper
end

Project/app/helpers/posts_helper.rb
module PostsHelper
end

Project/app/helpers/team_helper.rb
module TeamHelper
end

Project/app/helpers/widgets_helper.rb
module WidgetsHelper
end

Project/app/views/pitches/_form.html.erb
<!-- Author Naguib -->

<%= form_for @pitch do |f| %>
 
  <% if @pitch.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@pitch.errors.count, "error") %> prohibited
        this Pitch from being saved:
      </h2>
      <ul>
        <% @pitch.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.collection_select :email, User.all, :email, :email, include_blank: false %>
  </p>

  <p>
    <%= f.label :brief_description %><br>
    <%= f.text_area :brief_description, :style => "width:400px;height:150px;" %>
  </p>

  <p>
    <%= f.label :link %><br>
    <%= f.text_field :link, :style => "width:400px;height:25px;" %>
  </p>

  <p>
    <%= f.label :full_description %><br>
    <%= f.text_area :full_description, :style => "width:400px;height:150px;" %>
  </p>
 


  <p>
    <%= f.submit %>
  </p>
 
<% end %>

Project/app/views/pitches/edit.html.erb
<!-- Author Naguib -->


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Frontpage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-frontpage.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" <%= link_to "Home", :controller => :pages, :action => :home2%></a>
                <a class="navbar-brand" <%= link_to "Events Calendar", :controller => :events, :action => :index%></a>
                <a class="navbar-brand" <%= link_to "Pitch Library", :controller => :pitches, :action => :index%></a>
               <!-- <a class="navbar-brand" <%= link_to "Log In/Sign Up", :controller => :pages, :action => :home  %></a>-->
            </div>
</nav>

<!-- Begining of the form code-->

<div class="container">
<h1>Idea2Business</h1>
<h5>Editing Idea</h5>
 
<%= form_for :pitch, url: pitch_path(@pitch), method: :patch do |f| %>
 
<%= render 'form' %>

<% end %>
 
<%= link_to 'Back', pitches_path %>
</div>

Project/app/views/pitches/evaluationForm.html.erb
<!-- This view to fill in the form and submit -->
<!-- Author Mariam Afifi -->


<form action="submitTheForm_pitches_path" id="IdeaConsultantEvaluationForm" method="get" onsubmit="return ValidateForm(this);">

<script type="text/javascript">
function ValidateForm(frm) {
if (frm.IdeatorName.value == "") { alert('Ideator name is required.'); frm.IdeatorName.focus(); return false; }
if (frm.IdeaConsultantName.value == "") { alert('Idea Consultant Name is required.'); frm.IdeaConsultantName.focus(); return false; }
if (frm.IdeaConsultantEmailAddress.value == "") { alert('Idea Consultant Email Address is required.'); frm.IdeaConsultantEmailAddress.focus(); return false; }
return true; }
</script>
<h1>Idea Consultant Evaluation Form</h1>
<table style="width: 700px; border: 0;" cellpadding="4" cellspacing="0">
<tr> <td colspan="2">
<br /> <b>Ideator</b>
</td> </tr> <tr> <td style="width:50%">
<label for="IdeatorName">Ideator name*:</label><br />
<input name="IdeatorName" type="text" maxlength="100" style="width: 300px;" />
</td> <td style="width:50%">

</td> </tr> <tr> <td>
<label for="IdeatorEmailAddress">Ideator Email Address:</label><br />
<input name="IdeatorEmailAddress" type="text" maxlength="50" style="width: 300px;" />
</td> <td>

</td> </tr> <tr> <td colspan="2">

<br /> <b>Idea Consultant</b>
</td> </tr> <tr> <td>
<label for="IdeaConsultantName">Idea Consultant name*:</label><br />
<input name="IdeaConsultantName" type="text" maxlength="100" style="width: 300px;" />
</td> <td>

</td> </tr> <tr> <td>
<label for="IdeaConsultantEmailAddress">Idea Consultant Email Address*:</label><br />
<input name="IdeaConsultantEmailAddress" type="text" maxlength="100" style="width: 300px;" />
</td> <td>


</td> </tr> <tr> <td colspan="2">
<br /> <b>Idea Consultant performance</b>
</td> </tr> <tr> <td>
<select name="Creativity" style="width:155px;">
<option value="">- Creativity -</option>
<option value="Poor">Poor</option>
<option value="Below Average">Below Average</option>
<option value="Average">Average</option>
<option value="Above Average">Above Average</option>
<option value="Excellent">Excellent</option>
<option value="N/A">N/A</option>
</select>  
<select name="OrganizationSkills" style="width:155px;">
<option value="">- Organization Skills -</option>
<option value="Poor">Poor</option>
<option value="Below Average">Below Average</option>
<option value="Average">Average</option>
<option value="Above Average">Above Average</option>
<option value="Excellent">Excellent</option>
<option value="N/A">N/A</option>
</select>
</td> <td>
 

</td> </tr> <tr> <td>
<select name="ProblemSolving" style="width:155px;">
<option value="">- Problem Solving -</option>
<option value="Poor">Poor</option>
<option value="Below Average">Below Average</option>
<option value="Average">Average</option>
<option value="Above Average">Above Average</option>
<option value="Excellent">Excellent</option>
<option value="N/A">N/A</option>
</select>  
<select name="Teamwork" style="width:155px;">
<option value="">- Teamwork -</option>
<option value="Poor">Poor</option>
<option value="Below Average">Below Average</option>
<option value="Average">Average</option>
<option value="Above Average">Above Average</option>
<option value="Excellent">Excellent</option>
<option value="N/A">N/A</option>
</select>
</td> <td>


</td> </tr> <tr> <td colspan="2">
<br />
<label for="Comments">Other comments:</label>
<textarea name="Comments" rows="7" cols="40" style="width: 650px;"></textarea>
</td> </tr> <tr> <td>
<br />
* - required fields
</td> <td>
<br />
<div style="float: right">

<input name="skip_Submit" type="submit" value="Submit" />

</td> </tr>
</table>
</form>

Project/app/views/pitches/index.html.erb
<!-- Author Naguib -->



<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Frontpage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-frontpage.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" <%= link_to "Home", :controller => :pages, :action => :home2%></a>
                <a class="navbar-brand" <%= link_to "Events Calendar", :controller => :events, :action => :index%></a>
                <a class="navbar-brand" <%= link_to "Pitch Library", :controller => :pitches, :action => :index%></a>
               <!-- <a class="navbar-brand" <%= link_to "Log In/Sign Up", :controller => :pages, :action => :home  %></a>-->
            </div>
</nav>

<!-- Begining of the form code-->

 <div class="container">
<h1>Idea2Business</h1>
<h3> Posted Ideas </h3> 

<br><br>
<table>
  <tr>
    <th>Title</th>
    <th>Brief Desc</th>
    <!-- <th>Full Desc</th> -->
    <th colspan="8"></th>
  </tr>
 
  <% @pitches.each do |pitch| %>
    <tr style="margin-top:20px;">
      <td><%= pitch.title %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <td><%= pitch.brief_description.truncate(125) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
      <!-- <td><%= pitch.full_description %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> -->
      <td><%= link_to 'Show', pitch_path(pitch) %>&nbsp;&nbsp;&nbsp;</td>      
      <% if current_user.admin %>
        <td><%= link_to 'Edit', edit_pitch_path(pitch) %>&nbsp;&nbsp;&nbsp;</td>
        <td><%= link_to 'Delete', pitch_path(pitch), method: :delete %></td>
      <% end %>
    </tr>
  <% end %>
</table>
</div>

Project/app/views/pitches/new.html.erb
<!DOCTYPE html>
<html lang="en">



<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Frontpage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-frontpage.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" <%= link_to "Home", :controller => :pages, :action => :home2%></a>
                <a class="navbar-brand" <%= link_to "Events Calendar", :controller => :events, :action => :index%></a>
                <a class="navbar-brand" <%= link_to "Pitch Library", :controller => :pitches, :action => :index%></a>
               <!-- <a class="navbar-brand" <%= link_to "Log In/Sign Up", :controller => :pages, :action => :home  %></a>-->
            </div>
</nav>

<!-- Begining of the form code-->


<div class="container">
<h1>Idea2Business</h1>
<h3>New Idea</h3>

<%= form_for :pitch, url: pitches_path do |f| %>

<%= render 'form' %>

<% end %>

<%= link_to 'Back', pitches_path %>

 </div>

Project/app/views/pitches/show.html.erb
<% 
    cookies[:pitch_id] = @pitch.id
    if current_user.is_Idea_Consultant 
        cookies[:consultant_id] = current_user.id 
    end 
%>

<!-- Page Content -->
<div class="container">

  <!-- Page Header -->
    <div class="row">
        <div class="col-lg-10">
            <h1 class="page-header"><%= @pitch.title %><hr></h1>
        </div>
    </div>
    <!-- /.row -->

    <div class="col-md-4 portfolio-item">
        <a href="#">
            <img class="img-responsive" src="<%= @pitch.url %>" alt="">
        </a>

        <h3>Ideator: <h5><%= @pitch.user.email %></h5></h3>
        <hr>
        <h3>Brief Description: <h5><%= @pitch.brief_description %></h5></h3>
        <hr>
        <h3>Full Desription:  <h5><%= @pitch.full_description %></h5></h3>
        <hr>
    </div>


</div>


<% @pitch.evalutions.each do |eval| %>
  <tr style="margin-top:20px;">
      <p>Evaluator: </p> 
      <p><%= eval.user.email %></p>
      <p>Evalution:</p>
      <p><%= eval.comment %></p>     
<% end %>

 <%= link_to 'Evaluate Idea Consultant', evaluateIdeaConsultant_pitch_path(@pitch) %>  
<form action="<%= submitTheEvaluation_pitch_path(@pitch) %>" id="EvaluateTheIdea" method="post" onsubmit="return ValidateForm(this);">
<label for="Evaluate">Evaluate The Idea</label><br />
<textarea name="Evaluate" rows="5" cols="40" style="width: 500px;"></textarea>
<br />
<div style="float: middle">

 <input name="post" type="submit" value="Post" />  



<div class="container">
    <div align="center">
        <% if current_user.is_Idea_Consultant %>
            <%= link_to 'Add consultancy', { :controller => 'consultancies', :action => 'new' } %>
            <br><br><br>
        <% end %>
        <h4>Consultancies</h4>
        <table style="width:100%">
            <th>
                <tr style="font-weight:bold">
                    <td>Consultant</td>
                    <td>Consultancy</td>
                    <% if @pitch.user == current_user %>
                        <td>Status</td>
                    <% end %>
                </tr>
            </th>
                <% @consultancies.each do |c| %>
                <tr>
                    <td style="width:20%"><%= c.consultant.email %></td>
                    <td style="width:60%"><%= c.body %></td>
                    <% if @pitch.user == current_user %>
                        <% if c.approved %>
                            <td style="width:20%;color:green">Approved</td>
                        <% else %>
                            <td style="width:20%"><%= button_to "Approve", { :controller => 'consultancies', :action => 'approve', :id => c.id } %></td>
                        <% end %>
                    <% end %>
                </tr>
            <% end %>
        </table>
    </div>
</div>

<%= link_to 'Evaluate Idea Consultant', evaluateIdeaConsultant_pitch_path(@pitch) %>  


<%= link_to 'Back', pitches_path %> 
<!-- 
| 
<%= link_to 'Edit', edit_pitch_path(@pitch) %>
 -->