Project/config/routes.rb
Rails.application.routes.draw do

  resources :blogs

  get 'answers/indexshow'

 

  resources :posts
 resources :widgets
  resources :answers

  resources :consultancies

  devise_for :views
  devise_for :users
  resources :events
 resources :pitches do
    member do
     get 'evaluateIdeaConsultant' 
     get 'submitTheForm'
     post 'submitTheEvaluation'
    end
  end
  resources :conversations do
  resources :messages
 end

resources :posts, :has_many => :answers

  resources :consultancies
  get 'pages/home'
  get 'users/show'
  get 'events/userview'
  get 'users/index'
  get 'users/edit'
  get 'pages/home2'
  get 'pages/home3'
  get 'pages/signup'
  get 'pages/login'
  get 'posts/index'
  root 'pages#home'
  get 'approve' => 'consultancies#approve'
  post 'approve' => 'consultancies#approve'
  match 'users/:id/approve'=> 'users#approve_user', :via => [:get], as: 'approve_user'
  

end

Project/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :post
  


end

Project/app/models/blog.rb
class Blog < ActiveRecord::Base
end

Project/app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base
	belongs_to :blog
end

Project/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pitches

end

Project/app/models/conversation.rb
class Conversation < ActiveRecord::Base

# belongs_to :sender, :foreign_key => :sender_id, class_name: ‘User’
# belongs_to :recipient, :foreign_key => :recipient_id, class_name: ‘User’

has_many :messages, dependent: :destroy
validates_uniqueness_of :sender_id, :scope => :recipient_id

# scope :between, -> (sender_id,recipient_id) do
#  where(“(conversations.sender_id =? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)”, sender_id,recipient_id, recipient_id, sender_id)
#  end
end

Project/app/models/createComment.rb
class CreateComments < ActiveRecord::Migration
  def change
    create_table :comments do |t|
      t.string :commenter
      t.text :body
 
      # this line adds an integer column called `article_id`.
      t.references :article, index: true
 
      t.timestamps null: false
    end
    add_foreign_key :comments, :pitches
  end
end

Project/app/models/evalution.rb
class Evalution < ActiveRecord::Base
  belongs_to :user
  belongs_to :pitch
end

Project/app/models/friendship.rb
class Friendship < ActiveRecord::Base
	  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

Project/app/models/message.rb
class Message < ActiveRecord::Base
 belongs_to :conversation
 belongs_to :user
 validates_presence_of :body, :conversation_id, :user_id
 
	def message_time
		t = Time.now
		t.strftime(" %a, %d %b at %I:%M%p")            #=> example: "wed, 29 Apr at 01:20AM"
	end
end

Project/app/models/notification.rb
class Notification < ActiveRecord::Base
end

Project/app/models/pitch.rb
class Pitch < ActiveRecord::Base
  has_many :evalutions
	def user
		return User.find_by_email(self.email)
	end

	def consultancies
		return Consultancy.where("pitch_id =?", self.id)
	end
end

Project/app/models/post.rb
class Post < ActiveRecord::Base
  # validates_presence_of :name, :title
  # validates_length_of :title, :minimum => 5
  has_many :answers
end

Project/app/models/team.rb
class Team < ActiveRecord::Base
	  has_many :users

		 
  belongs_to :pitch, :class_name => "Pitch"
end

Project/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :evalutions
        def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end


  def pitches
    return Pitch.where("email =?",self.email)
  end

end

Project/app/models/widget.rb
class Widget < ActiveRecord::Base
end

Project/app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]

  # This method is to view all case studies in the database
  # Author: Hussien Kamal
  def index
    @blogs = Blog.all
  end

  # This method is to show a specific case study
  # Author: Hussien Kamal
  def show
  end

  # This method is to make a new instance from the case studies
  # Author : Hussien Kamal
  def new
    @blog = Blog.new
  end

  # This method is to edit a specific case study
  # Author: Hussien Kamal
  def edit
  end

  # This method is to submit a new case study
  # Author: Hussien Kamal
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Case was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # This method is to update a specific case study
  # Author: Hussien Kamal
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Case was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # This method is to delete a specific case study
  # Author: Hussien Kamal
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Case was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.find(params[:id])
    end

    # This method identifies the case study parameters
    # Author: Hussien Kamal
    def blog_params
      params.require(:blog).permit(:title, :content)
    end
end

Project/app/helpers/answers_helper.rb
module AnswersHelper
end

Project/app/helpers/blogs_helper.rb
module BlogsHelper
end

Project/app/helpers/comment_helper.rb
module CommentHelper
end

Project/app/helpers/friendship_helper.rb
module FriendshipHelper
end

Project/app/helpers/posts_helper.rb
module PostsHelper
end

Project/app/helpers/team_helper.rb
module TeamHelper
end

Project/app/helpers/widgets_helper.rb
module WidgetsHelper
end

Project/app/views/blogs/_form.html.erb
<%= form_for(@blog) do |f| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% @blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content,  :size => "70x30" %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit Case' %>
  </div>
<% end %>

Project/app/views/blogs/edit.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" <%= link_to "Home", :controller => :pages, :action => :home2%></a>
                <a class="navbar-brand" <%= link_to "Events Calendar", :controller => :events, :action => :index%></a>
                <a class="navbar-brand" <%= link_to "Pitch Library", :controller => :pitches, :action => :index%></a>
               <!-- <a class="navbar-brand" <%= link_to "Log In/Sign Up", :controller => :pages, :action => :home  %></a>-->
               <a class="navbar-brand" <%= link_to "Case Studies", :controller => :blogs, :action => :index%></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <!--<a href="#">About</a> -->
                    </li>
                    <li>
                        <!-- <a href="#">Services</a> -->
                    </li>
                    <li>
                        <!-- <a href="#">Contact</a> -->
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<h1>Editing Case</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

Project/app/views/blogs/index.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" <%= link_to "Home", :controller => :pages, :action => :home2%></a>
                <a class="navbar-brand" <%= link_to "Events Calendar", :controller => :events, :action => :index%></a>
                <a class="navbar-brand" <%= link_to "Pitch Library", :controller => :pitches, :action => :index%></a>
               <!-- <a class="navbar-brand" <%= link_to "Log In/Sign Up", :controller => :pages, :action => :home  %></a>-->
               <a class="navbar-brand" <%= link_to "Case Studies", :controller => :blogs, :action => :index%></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <!--<a href="#">About</a> -->
                    </li>
                    <li>
                        <!-- <a href="#">Services</a> -->
                    </li>
                    <li>
                        <!-- <a href="#">Contact</a> -->
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<p id="notice"><%= notice %></p>

<h1>Listing Cases</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <!--<th>Content</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= link_to 'Show', blog %></td>
        <%if current_user.admin%>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if current_user.is_Ideator%>
<%= link_to 'New Case', new_blog_path %>
<%end%>

Project/app/views/blogs/new.html.erb
 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" <%= link_to "Home", :controller => :pages, :action => :home2%></a>
                <a class="navbar-brand" <%= link_to "Events Calendar", :controller => :events, :action => :index%></a>
                <a class="navbar-brand" <%= link_to "Pitch Library", :controller => :pitches, :action => :index%></a>
               <!-- <a class="navbar-brand" <%= link_to "Log In/Sign Up", :controller => :pages, :action => :home  %></a>-->
               <a class="navbar-brand" <%= link_to "Case Studies", :controller => :blogs, :action => :index%></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <!--<a href="#">About</a> -->
                    </li>
                    <li>
                        <!-- <a href="#">Services</a> -->
                    </li>
                    <li>
                        <!-- <a href="#">Contact</a> -->
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<h1>New Case</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_path %>

Project/app/views/blogs/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
 <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" <%= link_to "Home", :controller => :pages, :action => :home2%></a>
                <a class="navbar-brand" <%= link_to "Events Calendar", :controller => :events, :action => :index%></a>
                <a class="navbar-brand" <%= link_to "Pitch Library", :controller => :pitches, :action => :index%></a>
               <!-- <a class="navbar-brand" <%= link_to "Log In/Sign Up", :controller => :pages, :action => :home  %></a>-->
               <a class="navbar-brand" <%= link_to "Case Studies", :controller => :blogs, :action => :index%></a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <!--<a href="#">About</a> -->
                    </li>
                    <li>
                        <!-- <a href="#">Services</a> -->
                    </li>
                    <li>
                        <!-- <a href="#">Contact</a> -->
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @blog.content %>
</p>


<%= link_to 'Back', blogs_path %>