Project/config/routes.rb
Rails.application.routes.draw do

  resources :blogs

  get 'answers/indexshow'

 

  resources :posts
 resources :widgets
  resources :answers

  resources :consultancies

  devise_for :views
  devise_for :users
  resources :events
 resources :pitches do
    member do
     get 'evaluateIdeaConsultant' 
     get 'submitTheForm'
     post 'submitTheEvaluation'
    end
  end
  resources :conversations do
  resources :messages
 end

resources :posts, :has_many => :answers

  resources :consultancies
  get 'pages/home'
  get 'users/show'
  get 'events/userview'
  get 'users/index'
  get 'users/edit'
  get 'pages/home2'
  get 'pages/home3'
  get 'pages/signup'
  get 'pages/login'
  get 'posts/index'
  root 'pages#home'
  get 'approve' => 'consultancies#approve'
  post 'approve' => 'consultancies#approve'
  match 'users/:id/approve'=> 'users#approve_user', :via => [:get], as: 'approve_user'
  

end

Project/app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :post
  


end

Project/app/models/blog.rb
class Blog < ActiveRecord::Base
end

Project/app/models/blog_comment.rb
class BlogComment < ActiveRecord::Base
	belongs_to :blog
end

Project/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :pitches

end

Project/app/models/conversation.rb
class Conversation < ActiveRecord::Base

# belongs_to :sender, :foreign_key => :sender_id, class_name: ‘User’
# belongs_to :recipient, :foreign_key => :recipient_id, class_name: ‘User’

has_many :messages, dependent: :destroy
validates_uniqueness_of :sender_id, :scope => :recipient_id

# scope :between, -> (sender_id,recipient_id) do
#  where(“(conversations.sender_id =? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)”, sender_id,recipient_id, recipient_id, sender_id)
#  end
end

Project/app/models/createComment.rb
class CreateComments < ActiveRecord::Migration
  def change
    create_table :comments do |t|
      t.string :commenter
      t.text :body
 
      # this line adds an integer column called `article_id`.
      t.references :article, index: true
 
      t.timestamps null: false
    end
    add_foreign_key :comments, :pitches
  end
end

Project/app/models/evalution.rb
class Evalution < ActiveRecord::Base
  belongs_to :user
  belongs_to :pitch
end

Project/app/models/friendship.rb
class Friendship < ActiveRecord::Base
	  belongs_to :user
  belongs_to :friend, :class_name => "User"
end

Project/app/models/message.rb
class Message < ActiveRecord::Base
 belongs_to :conversation
 belongs_to :user
 validates_presence_of :body, :conversation_id, :user_id
 
	def message_time
		t = Time.now
		t.strftime(" %a, %d %b at %I:%M%p")            #=> example: "wed, 29 Apr at 01:20AM"
	end
end

Project/app/models/notification.rb
class Notification < ActiveRecord::Base
end

Project/app/models/pitch.rb
class Pitch < ActiveRecord::Base
  has_many :evalutions
	def user
		return User.find_by_email(self.email)
	end

	def consultancies
		return Consultancy.where("pitch_id =?", self.id)
	end
end

Project/app/models/post.rb
class Post < ActiveRecord::Base
  # validates_presence_of :name, :title
  # validates_length_of :title, :minimum => 5
  has_many :answers
end

Project/app/models/team.rb
class Team < ActiveRecord::Base
	  has_many :users

		 
  belongs_to :pitch, :class_name => "Pitch"
end

Project/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :evalutions
        def active_for_authentication? 
    super && approved? 
  end 

  def inactive_message 
    if !approved? 
      :not_approved 
    else 
      super # Use whatever other message 
    end 
  end


  def pitches
    return Pitch.where("email =?",self.email)
  end

end

Project/app/models/widget.rb
class Widget < ActiveRecord::Base
end

Project/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  #Author OmarHisham
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  #Author OmarHisham
  def show
    @new_ans = Answer.new
    @new_ans.post_id = @post.id
  end

  # GET /posts/new
  #Author OmarHisham
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  #Author OmarHisham
  def edit
  end

  # Create new question and save it to table
  # Author OmarHisham
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # popup notification after posting
  #Author OmarHisham
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # remove from table
  # Author OmarHisham
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #Author OmarHisham
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    #Author OmarHisham
    def post_params
      params.require(:post).permit(:Category, :Question)
    end
end

Project/app/helpers/answers_helper.rb
module AnswersHelper
end

Project/app/helpers/blogs_helper.rb
module BlogsHelper
end

Project/app/helpers/comment_helper.rb
module CommentHelper
end

Project/app/helpers/friendship_helper.rb
module FriendshipHelper
end

Project/app/helpers/posts_helper.rb
module PostsHelper
end

Project/app/helpers/team_helper.rb
module TeamHelper
end

Project/app/helpers/widgets_helper.rb
module WidgetsHelper
end

Project/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Category %><br>
    <%= f.text_field :Category %>
  </div>
  <div class="field">
    <%= f.label :Question %><br>
    <%= f.text_area :Question %>
  </div>
  <div class="actions">
    <%= f.submit 'Ask' %>
  </div>
   <% end %>

Project/app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

Project/app/views/posts/index.html.erb
<!DOCTYPE html>
<html lang="en">



<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Frontpage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-frontpage.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    
                </button>
                <a class="navbar-brand" <%= link_to "Home", :controller => :pages, :action => :home2%></a>
                <a class="navbar-brand" <%= link_to "Events Calendar", :controller => :events, :action => :index%></a>
                <a class="navbar-brand" <%= link_to "Pitch Library", :controller => :pitches, :action => :index%></a>
               <!-- <a class="navbar-brand" <%= link_to "Log In/Sign Up", :controller => :pages, :action => :home  %></a>-->
            
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Image Background Page Header -->
    <!-- Note: The background image is set within the business-casual.css file. -->
    <!--<header class="business-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="tagline">Business Namesss or Tagline</h1>
                </div>
            </div>
        </div> 
    </header>-->

    <!-- Page Content -->
    <div class="container">

        

        

        

       <!-- <div class="row">
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt="">
                <h2>Marketing Box #1</h2>
                <p>These marketing boxes are a great place to put some information. These can contain summaries of what the company does, promotional information, or anything else that is relevant to the company. These will usually be below-the-fold.</p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt="">
                <h2>Marketing Box #2</h2>
                <p>The images are set to be circular and responsive. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt="">
                <h2>Marketing Box #3</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
            </div>
        </div>
        -->
        <!-- /.row -->

        <hr>

        

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>

<p id="notice"><%= notice %></p>

<h1>Questions</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Question</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.Category %></td>
        <td><%= post.Question %></td>
        <!--<td><%= link_to 'Edit', edit_post_path(post) %></td>-->
        <td> <%= link_to 'Show', post %></td>
        <!--check wether the user is admin or not to view button-->
        <%if current_user.admin?%>

        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
   <!--check wether the user is ideator or not to view button-->
  <%if current_user.is_Ideator?%>
<%= link_to 'Ask question', new_post_path %>
  <%end%>
 <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; TekLife 2015</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>

Project/app/views/posts/new.html.erb
<h1>Ask question</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

Project/app/views/posts/show.html.erb
<!DOCTYPE html>
<html lang="en">



<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Frontpage - Start Bootstrap Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="css/business-frontpage.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    
                </button>
                <a class="navbar-brand" <%= link_to "Home", :controller => :pages, :action => :home2%></a>
                <a class="navbar-brand" <%= link_to "Events Calendar", :controller => :events, :action => :index%></a>
                <a class="navbar-brand" <%= link_to "Pitch Library", :controller => :pitches, :action => :index%></a>
               <!-- <a class="navbar-brand" <%= link_to "Log In/Sign Up", :controller => :pages, :action => :home  %></a>-->
            
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Image Background Page Header -->
    <!-- Note: The background image is set within the business-casual.css file. -->
    <!--<header class="business-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="tagline">Business Namesss or Tagline</h1>
                </div>
            </div>
        </div> 
    </header>-->

    <!-- Page Content -->
    <div class="container">

      

        

        

       <!-- <div class="row">
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt="">
                <h2>Marketing Box #1</h2>
                <p>These marketing boxes are a great place to put some information. These can contain summaries of what the company does, promotional information, or anything else that is relevant to the company. These will usually be below-the-fold.</p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt="">
                <h2>Marketing Box #2</h2>
                <p>The images are set to be circular and responsive. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
            </div>
            <div class="col-sm-4">
                <img class="img-circle img-responsive img-center" src="http://placehold.it/300x300" alt="">
                <h2>Marketing Box #3</h2>
                <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
            </div>
        </div>
        -->
        <!-- /.row -->

        <hr>

        

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @post.Category %>
</p>

<p>
  <strong>Question:</strong>
  <%= @post.Question %>
</p>
<!-- This view : Check if consultant view the form of answering else answers only viewed--> 
<!-- Author :Monica -->
<p>
</br>
<h2>Answers</h2>

<% @post.answers.each do |a| %>
<p>
    <%= a.Answerer %> </p>
    <p>
    <%= a.body %></p>
<% end %>

   <br>



   <p>
<% if current_user.is_Idea_Consultant %>
  <%= form_for @new_ans, url: answers_path do |f| %>
    <b>Answer body</b><br>
    <%= f.text_field :body %>
    <%= f.hidden_field :post_id %>
 
  <p>
    <%= f.submit %>
  </p>
   
<% end %>
<% end %>




<!--<%= link_to 'Edit', edit_post_path(@post) %>--> 
<%= link_to 'Back', posts_path %>
 
</p>
<footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; TekLife 2015</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>
 </div>

 