config/routes.rb
Rails.application.routes.draw do
  resources :consultancies

  devise_for :views
  devise_for :users
  resources :events
 resources :pitches do
    member do
     get 'evaluateIdeaConsultant' 
     get 'submitTheForm'
    end
  end

  resources :consultancies
  get 'pages/home'
  get 'users/show'
  get 'events/userview'
  get 'users/index'
  get 'users/edit'
  get 'pages/home2'
  get 'pages/home3'
  get 'pages/signup'
  get 'pages/login'
  root 'pages#home'
  get 'approve' => 'consultancies#approve'
  post 'approve' => 'consultancies#approve'
  match 'users/:id/approve'=> 'users#approve_user', :via => [:get], as: 'approve_user'
  

end

app/models/consultancy.rb
class Consultancy < ActiveRecord::Base
	
	def pitch
		if self.pitch_id
			return Pitch.find(self.pitch_id)
		else
			return Pitch.new
		end
	end

	def consultant
		return User.find(self.consaltant_id)
	end
end

app/controllers/consultancies_controller.rb
class ConsultanciesController < ApplicationController
  before_action :set_consultancy, only: [:show, :edit, :update, :destroy]

  # GET /consultancies
  # GET /consultancies.json
  def index
    @consultancies = Consultancy.all
  end

  # GET /consultancies/1
  # GET /consultancies/1.json
  def show
    @consultancy = Consultancy.find(params[:id])
  end

  # GET /consultancies/new
  def new
    @consultancy = Consultancy.new
    @consultancy.pitch_id = cookies[:pitch_id]
    @consultancy.consaltant_id = cookies[:consultant_id]    
  end

  # GET /consultancies/1/edit
  def edit
  end

  # POST /consultancies
  # POST /consultancies.json
  def create
    @consultancy = Consultancy.new(consultancy_params)
    respond_to do |format|
      @consultancy.pitch_id = cookies[:pitch_id]
      @consultancy.consaltant_id = cookies[:consultant_id]
      if @consultancy.save
        format.html { redirect_to :controller => 'pitches' ,:action => 'show', :id => @consultancy.pitch_id , notice: 'Consultancy was successfully created.' }
        format.json { render :show, status: :created, location: @consultancy }
      else
        format.html { render :new }
        format.json { render json: @consultancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consultancies/1
  # PATCH/PUT /consultancies/1.json
  def update
    respond_to do |format|
      if @consultancy.update(consultancy_params)
        format.html { redirect_to @consultancy, notice: 'Consultancy was successfully updated.' }
        format.json { render :show, status: :ok, location: @consultancy }
      else
        format.html { render :edit }
        format.json { render json: @consultancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consultancies/1
  # DELETE /consultancies/1.json
  def destroy
    @consultancy.destroy
    respond_to do |format|
      format.html { redirect_to consultancies_url, notice: 'Consultancy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    @consultancy = Consultancy.find(params[:id])
    @consultancy.approved = true
    @consultancy.save
    redirect_to :controller => 'pitches', :action => 'show', :id => @consultancy.pitch_id
  end

  def deny
    @consultancy = Consultancy.find(params[:id])
    @consultancy.approved = false
    @consultancy.save
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultancy
      @consultancy = Consultancy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def consultancy_params
      params.require(:consultancy).permit(:pitch_id, :body, :consaltant_id, :approved)
    end
end

app/helpers/consultancies_helper.rb
module ConsultanciesHelper
end

app/views/consultancies/_form.html.erb
<head>    
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="css/business-frontpage.css" rel="stylesheet">

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>


    <!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" <%= link_to "Home", :controller => :pages, :action => :home2%></a>
        <a class="navbar-brand" <%= link_to "Events Calendar", :controller => :events, :action => :index%></a>
        <a class="navbar-brand" <%= link_to "Pitch Library", :controller => :pitches, :action => :index%></a>
       <!-- <a class="navbar-brand" <%= link_to "Log In/Sign Up", :controller => :pages, :action => :home  %></a>-->
    </div>
</nav>
  <%
    cookies[:pitch_id] = cookies[:pitch_id]
    cookies[:consultant_id] = cookies[:consultant_id]
  %>
<%= form_for(@consultancy) do |f| %>
  <% if @consultancy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@consultancy.errors.count, "error") %> prohibited this consultancy from being saved:</h2>

      <ul>
      <% @consultancy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <%= f.label :pitch_id %><br>
    <%= f.number_field :pitch_id %>
  </div> -->
  <input name="pitch_id" type="hidden" value="<%=@pitch_id%>" />
  <%= @pitch_id %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, :style => "width:400px;height:150px;" %>
  </div>
  <!-- <div class="field">
    <%= f.label :consaltant_id %><br>
    <%= f.number_field :consaltant_id %>
  </div> -->
  <!-- <div class="field">
    <%= f.label :approved %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <%= f.check_box :approved %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/consultancies/edit.html.erb
<h1>Editing Consultancy</h1>

<%= render 'form' %>

<%= link_to 'Show', @consultancy %> |
<%= link_to 'Back', consultancies_path %>

app/views/consultancies/index.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" <%= link_to "Home", :controller => :pages, :action => :home2%></a>
          <a class="navbar-brand" <%= link_to "Events Calendar", :controller => :events, :action => :index%></a>
          <a class="navbar-brand" <%= link_to "Pitch Library", :controller => :pitches, :action => :index%></a>
         <!-- <a class="navbar-brand" <%= link_to "Log In/Sign Up", :controller => :pages, :action => :home  %></a>-->
      </div>
</nav>

<p id="notice"><%= notice %></p>

<h1>Listing Consultancies</h1>

<table style="width:100%">
  <thead>
    <tr>
      <th>Pitch</th>
      <th>Body</th>
      <th>Consaltant</th>
      <th>Approved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @consultancies.each do |consultancy| %>
      <tr>
        <td><%= consultancy.pitch.title %></td>
        <td><%= consultancy.body %></td>
        <td><%= consultancy.consaltant.email %></td>
        <td><%= consultancy.approved %></td>
        <td><%= link_to 'Show', consultancy %></td>
        <td><%= link_to 'Edit', edit_consultancy_path(consultancy) %></td>
        <td><%= link_to 'Destroy', consultancy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Consultancy', new_consultancy_path %>

app/views/consultancies/new.html.erb
<h1>New Consultancy</h1>

<%= render 'form' %>

<%= link_to 'Back', consultancies_path %>

app/views/consultancies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pitch:</strong>
  <%= @consultancy.pitch_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @consultancy.body %>
</p>

<p>
  <strong>Consaltant:</strong>
  <%= @consultancy.consaltant_id %>
</p>

<p>
  <strong>Approved:</strong>
  <%= @consultancy.approved %>
</p>

<%= link_to 'Edit', edit_consultancy_path(@consultancy) %> |
<%= link_to 'Back', consultancies_path %>